name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        uses: SpicyPizza/create-envfile@v1
        env: 
          NASA: ${{ secrets.NASA_POWER_API_KEY }}
          WIND: ${{ secrets.WIND_TOOLKIT_API_KEY }}
          OPEN: ${{ secrets.OPEN_WEATHER_API_KEY }}
          EMAIL: ${{ secrets.EMAIL }}
        with:
          envkey_NASA_POWER_API_KEY: ${{ secrets.NASA_POWER_API_KEY }}
          envkey_WIND_TOOLKIT_API_KEY: ${{ secrets.WIND_TOOLKIT_API_KEY }}
          envkey_OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
          envkey_EMAIL: ${{ secrets.EMAIL }}
          envkey_NODE_ENV: "test"
      - name: Check env
        run: cat .env
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm test

      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
